import type { Metadata } from "next";
import "./globals.css";
import { auth } from "@/auth";
import Login from "@/components/auth-components";
import { SessionProvider } from "next-auth/react";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { WithAuth } from "./WithAuth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  const locale = await getLocale();
  const messages = await getMessages();

  const login = <Login user={session?.user} />;
  return (
    <html lang={locale} className="bg-primary text-secondary">
      <body className="flex flex-col min-h-screen m-0 box-border sm:flex-row xl:flex-col sm:justify-between">
        <NextIntlClientProvider messages={messages}>
          <div id="content" className="mb-24 sm:mb-8 grow mt-4 mx-2">
            <main className="flex flex-row justify-start items-start">
              <div className="flex flex-col items-center justify-start grow xl:pb-16">
                <SessionProvider>
                  <WithAuth>{children}</WithAuth>
                </SessionProvider>
              </div>
            </main>
          </div>
          <footer>
            <div className="h-16 mt-auto touch-none flex border-t flex-row items-center justify-evenly fixed bottom-0 left-0 w-screen bg-primary">
              {login}
            </div>
          </footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
